config:
  service:
    name: user-registration-worker
    id: a8201b36-694d-4904-930b-fb79e4888888
  swagger:
    info:
      title: User Registration Gateway
      description: Interface for user registrations
  cors:
    allowedOrigins: http://localhost:8080

spring:
  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS users

  liquibase:
    change-log: classpath:/changeLog.json
    enabled: true
    liquibase-schema: users
    database-change-log-lock-table: DATABASECHANGELOGLOCK
    database-change-log-table: DATABASECHANGELOG

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_HOST:5627}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 3
          max-interval: 5s
          multiplier: 2

  jackson:
    serialization:
      fail_on_empty_beans: false

  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

logging:
  level:
    ROOT: INFO